/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.78).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Employer;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2026-04-28T20:38:41.609801331Z[GMT]")
@Validated
public interface EmployersApi {

    @Operation(summary = "Отримати всіх роботодавців", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Список роботодавців успішно отримано", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Employer.class)))) })
    @RequestMapping(value = "/employers",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Employer>> employersGet();


    @Operation(summary = "Видалити роботодавця", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Роботодавця видалено") })
    @RequestMapping(value = "/employers/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> employersIdDelete(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") Integer id
);


    @Operation(summary = "Отримати дані роботодавця за ID", description = "", tags={  })
    @ApiResponses(value = {  })
    @RequestMapping(value = "/employers/{id}",
        method = RequestMethod.GET)
    ResponseEntity<Void> employersIdGet(@Parameter(in = ParameterIn.PATH, description = "", required=true, schema=@Schema()) @PathVariable("id") Integer id
);


    @Operation(summary = "Додати нового роботодавця", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Роботодавця створено") })
    @RequestMapping(value = "/employers",
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> employersPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody Employer body
);

}

